apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: infrastructure
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/your-repo-name.git #your github repo
    targetRevision: main
    path: #path/folder in the repo where the file is saved

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
