apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: devops-portfolio
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Nifemi-Stephen/devops-website.git
    targetRevision: HEAD
    path: helm

  destination:
    server: https://kubernetes.default.svc
    namespace: devops-eks

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
