# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ashaolu/devops-portfolio
  # Overrides the image tag whose default is the chart appVersion.
  tag: "a2401fea0ceee36e121e21fba80f04206459d891"
